server:
  port: 1008

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    address:
      redis://192.168.92.56:6379,//192.168.92.64:6379,//192.168.92.65:6379,//192.168.92.56:6380,//192.168.92.64:6380,//192.168.92.65:6380

cloud:
  retry:
    interval-in-seconds: 30

  trace:
    with-header: false

  jwt:
    app-id: 1008
    secret: sample.app20200808qa1z3838wsxedc3rfv4tgbyhnujm5ikolp9ttt$QA0ZWSXED2CRFV8TGB2YHNU7JM3IKO8LPa12*@(cloud.jwt)
    ttl-in-hours: 24
    multi-login-check: true

  server:
    oauth:
      sample_service:
        app-id: 1008
        key: oauth1_consumer_key_of_sample_service
        secret: oauth1_consumer_secret_of_sample_service

  client:
    oauth:
      remote-service-1:
        url: https://promotion-service.51zhaoyou.com/test
        key: Zpetrolservice51serviceY
        secret: 215419DCDF9E9F5160545E517624FEBB

    signer:
      remote-service-3:
        url: https://open-data.51zhaoyou.com/test
        app-id: 2824
        app-key: F96502BD5D1D4224B55FE24503EFB52C

    remote-service-2:
      url: $cloud.client.remote-service-2.url$